changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Security
      labels:
        - security
    - title: Dependencies
      labels:
        - dependencies
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"
